### ISSUE TITLE
Unsupported architecture error (Apple Silicon)

### ISSUE THREAD

**Issue by NetOpWibby** [MarkTiedemann/deno-dart-sass#1]
Doesn't look like pre-built binaries for Dart Sass on Apple Silicon exist yet.

https://github.com/sass/dart-sass/issues/1125

EDIT: No wait, [here's an ARM64 release](https://github.com/sass/dart-sass/releases/tag/1.51.0).

**Comment by MarkTiedemann** [comment]
@NetOpWibby Thanks for the issue!

Seems like dart-sass v1.49.11 was the first with ARM64 support. I have added logic to support this: https://github.com/MarkTiedemann/deno-dart-sass/commit/030aa8e4e3ec497d102b3541e9edb864821d3a6b.

Can you test whether this implementation works for you? I don't have a Mac at the moment.

**Comment by NetOpWibby** [comment]
It works!
